version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - checkout
  - package
  - test
  - upload
steps:
  main_clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "checkout"
  MyDockerImage:
    title: "Building Docker image"
    type: "build"
    image_name: "lexhider/my-flask-image"
    working_directory: "./"
    tag: "v1.0.0"
    dockerfile: "Dockerfile"
    stage: "package"
    disable_push: true
  RunTests:
    title: run unit tests
    image: "${{MyDockerImage}}"
    stage: test
    commands:
      - pip install pytest
      - pytest
  DoPush:
    title: push image to dockerhub
    stage: upload
    tag: "${{CF_BRANCH}}"
    candidate: "${{MyDockerImage}}"
    image_name: lexhider/my-flask-image
    registry: dockerhub
