version: '1.0'
stages:
  - build
  - test
  - push
steps:

  BuildingDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: codenough/pythonflasksampleapp
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
    metadata:
      set:
        - CF_QUALITY: true
        - progress: 80%
        - url: ${{CF_COMMIT_URL}}

  MyUnitTests: 
    title: Running Unit tests 
    stage: test 
    image: ${{BuildingDockerImage}} 
    commands:
      - python setup.py test
  push_step:
    type: push
    stage: push
    description: Push to docker registry
    candidate: ${{BuildingDockerImage}}
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}
    registry: dockerhub
